name: mcm_2021_c
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - anaconda
  - pytorch
  - torchvision
  - torchaudio
  - opencv
  - imbalanced-learn

# Important: please choose the only cuda version that your gpu use
# For more infomation: https://pytorch.org/get-started/locally/
  - cpuonly # Comment this line if you are going to use a gpu for training
  # - cudatoolkit=11.0 # Uncomment this line if your are going to use a gpu for
  #                      training, and change the version corresponding to the
  #                      CUDA version in your system.
